version: "3.7"

services:
  prod:
    labels:
      - Author="Lucas Eliaquim"
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    stdin_open: true

  dev:
    labels:
      - Author="Lucas Eliaquim"
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    stdin_open: true

  mongo:
    labels:
      - Author="Lucas Eliaquim"
    image: mongo:3.6.21
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_OPTIONS_EDITORTHEME: dracula
    links:
      - mongo

volumes:
  mongodb_data:
