DATABASE_NAME = 'botlander_database'
DATABASE_HOST = 'mongo'
DATABASE_USERNAME = 'root'
DATABASE_PASSWORD = 'admin'
DATABASE_AUTHENTICATION_SOURCE = 'admin'

WAITRESS_HOST = '0.0.0.0'
WAITRESS_PORT = 5000
WAITRESS_THREADS = 2

JWT_SECRET_KEY = 'super secret'
JWT_REFRESH_TOKEN_EXPIRES = False
JWT_ACCESS_TOKEN_EXPIRES = 3600
